version: "3.9"

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - BIND_ADDR=:8080
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=user
      - DB_PASSWORD=pass
      - DB_NAME=postgres
      - DB_SSL_MODE=disable
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    healthcheck:
      test: PGPASSWORD='pass' psql -U user --command='SELECT 1'
      interval: 1s
      timeout: 2s
      retries: 5

volumes:
  postgres_volume: