version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: cmd/apiserver/Dockerfile
    ports:
      - 8080:8080
    environment:
      - BIND_ADDR=:8080
      - DSN=postgres://db/todo_lists_db?sslmode=disable&user=user&password=pass
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=todo_lists_db
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    healthcheck:
      test: PGPASSWORD='pass' psql -U user todo_lists_db --command='SELECT 1'
      interval: 1s
      timeout: 2s
      retries: 5

volumes:
  postgres_volume: